### PR TITLE
Create Poolmaster_Smart Button 3rd

### PR DESCRIPTION
**Pull request by bbwouters**
unctionality added: you can stop the Filtration-pump by double tapping the push-button in case you want to do a backwash or need to do some maintenance on your system (and you don't have a mobile or computer at hand to use the API). Double tapping it again will restart the pump. The single tap toggle screen functionality and the 2 sec long press reset functionality remained.

Green, red led's are correctly set at boot-up in the setup (not sure they were correctly set before) and also the pump is started at boot-up if in time window.
Adds a new task: Task t6(10, ButtonCallback);
Needs 2 libraries: bounce2.h and ButtonEvents.h, but no longer requires JC_Button.h

### CODE REVIEW

**Comment by Loic74650** [comment]
Boris I just started to have a look at your code and I see a couple issues which need to be discussed. 

-	You are replacing many variables (board pins, IP address, temp probes addresses, MAC address, etc) with your own settings which work for your setup, which makes sense. But that means they won’t work for other people’s  setup anymore. I think we need to externalize all those variables into a separate config file so that each person keeps his own config file locally and does not commit it, WDYT?

-	There were some commits to the master since you made your code changes and pull request, so you need to refresh your code and do your pull request again. The changes are concerning the RTC module. An alternative is that I ignore the changes in your pull request which concern the RTC, I will check how to do that (I have litlle experience in this process)

**Comment by bbwouters** [comment]
see below. 





Boris I just started to have a look at your code and I see a couple issues which need to be discussed. 

    * 

You are replacing many variables (board pins, IP address, temp probes addresses, MAC address, etc) with your own settings which work for your setup, which makes sense. But that means they won’t work for other people’s setup anymore. I think we need to externalize all those variables into a separate config file so that each person keeps his own config file locally and does not commit it, WDYT? *** Indeed. Externalizing solves this but brings it own level of complexity. Another option is to group it in the code, as now it is a bit all over the place, so people working on the code only need to adjust one section to their own config. 
    * 

There were some commits to the master since you made your code changes and pull request, so you need to refresh your code and do your pull request again. The changes are concerning the RTC module. An alternative is that I ignore the changes in your pull request which concern the RTC, I will check how to do that (I have litlle experience in this process). *** I noticed today, I am no expert on this process either :-) By the way I plan to update the RTC so it gets compares the time with the time of a timeserver. In this case no need to update the RTC at first usage unless timeserver can not be reached.

**Comment by Loic74650** [comment]
Hi Boris

-	Sylvain, another contributor has reviewed and tested your code and I will do the same this WE. I have already two requests: 
o	could you add a flag so that one can choose between Active High or Low for the button? By default it should be Active Low as indicated on the wiring diagram of the project. 
o	Please update the list of dependencies in the code header and in the “libraries” folder with the two new libraries you have added and minus the one you removed

FYI I have created a new branch called “develop” towards which future pull-request should be directed instead of towards the master, thanks.

Cheers
Loic

**Comment by Loic74650** [comment]
HI Boris,
I merged your code to the "develop" branch but from my repository because I did not keep some of the setup variables changes, so I will close this pull request

**Pull request closed without merging**
